# SPDX-FileCopyrightText: 2024 WithLithum <WithLithum@outlook.com>
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

# .vscode files
[[annotations]]
path = ".vscode/**/*"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# i10n files
[[annotations]]
path = "i10n/**/*"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# bin/obj files

[[annotations]]
path = "**/bin/**/*"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "**/obj/**/*"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# .idea files

[[annotations]]
path = ".idea/**/*"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# DotSettings files

[[annotations]]
path = "src/MetaCraft.sln.DotSettings.user"
SPDX-FileCopyrightText = "2024 WithLithum <WithLithum@outlook.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
