//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaCraft.Locales {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MetaCraft.Locales.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorExceptionOccurred {
            get {
                return ResourceManager.GetString("ErrorExceptionOccurred", resourceCulture);
            }
        }
        
        internal static string ErrorExceptionOccurredWithMessage {
            get {
                return ResourceManager.GetString("ErrorExceptionOccurredWithMessage", resourceCulture);
            }
        }
        
        internal static string InspectCommandDescription {
            get {
                return ResourceManager.GetString("InspectCommandDescription", resourceCulture);
            }
        }
        
        internal static string InspectCommandFileNotFound {
            get {
                return ResourceManager.GetString("InspectCommandFileNotFound", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageId {
            get {
                return ResourceManager.GetString("InspectCommandPackageId", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageVersion {
            get {
                return ResourceManager.GetString("InspectCommandPackageVersion", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageTime {
            get {
                return ResourceManager.GetString("InspectCommandPackageTime", resourceCulture);
            }
        }
        
        internal static string InspectCommandNotAPackage {
            get {
                return ResourceManager.GetString("InspectCommandNotAPackage", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackagePlatform {
            get {
                return ResourceManager.GetString("InspectCommandPackagePlatform", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageSize {
            get {
                return ResourceManager.GetString("InspectCommandPackageSize", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageDescription {
            get {
                return ResourceManager.GetString("InspectCommandPackageDescription", resourceCulture);
            }
        }
        
        internal static string InspectCommandPackageLicence {
            get {
                return ResourceManager.GetString("InspectCommandPackageLicence", resourceCulture);
            }
        }
        
        internal static string InspectCommandDependencies {
            get {
                return ResourceManager.GetString("InspectCommandDependencies", resourceCulture);
            }
        }
        
        internal static string InspectCommandConflictsWith {
            get {
                return ResourceManager.GetString("InspectCommandConflictsWith", resourceCulture);
            }
        }
        
        internal static string InspectCommandRefProvides {
            get {
                return ResourceManager.GetString("InspectCommandRefProvides", resourceCulture);
            }
        }
        
        internal static string InspectCommandMaintainers {
            get {
                return ResourceManager.GetString("InspectCommandMaintainers", resourceCulture);
            }
        }
        
        internal static string InspectCommandAuthors {
            get {
                return ResourceManager.GetString("InspectCommandAuthors", resourceCulture);
            }
        }
        
        internal static string InstallCommandDescription {
            get {
                return ResourceManager.GetString("InstallCommandDescription", resourceCulture);
            }
        }
        
        internal static string InstallCommandArgumentFile {
            get {
                return ResourceManager.GetString("InstallCommandArgumentFile", resourceCulture);
            }
        }
        
        internal static string InstallCommandOptionForce {
            get {
                return ResourceManager.GetString("InstallCommandOptionForce", resourceCulture);
            }
        }
        
        internal static string InstallCommandPlatformNotSupported {
            get {
                return ResourceManager.GetString("InstallCommandPlatformNotSupported", resourceCulture);
            }
        }
        
        internal static string RemoveCommandDescription {
            get {
                return ResourceManager.GetString("RemoveCommandDescription", resourceCulture);
            }
        }
        
        internal static string RemoveCommandArgumentPackage {
            get {
                return ResourceManager.GetString("RemoveCommandArgumentPackage", resourceCulture);
            }
        }
        
        internal static string RemoveCommandArgumentVersion {
            get {
                return ResourceManager.GetString("RemoveCommandArgumentVersion", resourceCulture);
            }
        }
        
        internal static string RemoveCommandOptionForce {
            get {
                return ResourceManager.GetString("RemoveCommandOptionForce", resourceCulture);
            }
        }
        
        internal static string RemoveCommandInvalidVersion {
            get {
                return ResourceManager.GetString("RemoveCommandInvalidVersion", resourceCulture);
            }
        }
        
        internal static string RemoveCommandNonExistent {
            get {
                return ResourceManager.GetString("RemoveCommandNonExistent", resourceCulture);
            }
        }
    }
}
